export const sessions = [
  {
    id: 1,
    title: "Elite Shooting Clinic",
    coach: "Tim Turk",
    sport: "Hockey",
    skill_level: "AAA",
    age_min: 10,
    age_max: 14,
    city: "Brampton",
    province: "ON",
    price: 85,
    schedule: "Sundays, 10:00 AM - 12:00 PM",
    spots_available: 12,
    session_type: "Multiple Sessions",
    description:
      "Master the art of scoring with NHL shooting coach Tim Turk. This clinic focuses on wrist shots, snap shots, and one-timers with game-situation drills that translate directly to competitive play.",
  },
  {
    id: 2,
    title: "Hockey Skills Development Program",
    coach: "Tim Turk",
    sport: "Hockey",
    skill_level: "AA/AAA",
    age_min: 8,
    age_max: 12,
    city: "Brampton",
    province: "ON",
    price: 75,
    schedule: "Saturdays, 8:00 AM - 9:30 AM",
    spots_available: 16,
    session_type: "Multiple Sessions",
    description:
      "Comprehensive skills development covering skating, puck handling, passing, and hockey IQ. Perfect for competitive players looking to elevate their game to the next level.",
  },
  {
    id: 3,
    title: "Power Skating Fundamentals",
    coach: "Jodi Figliomeni - JF Power Elite",
    sport: "Power Skating",
    skill_level: "A/AA",
    age_min: 7,
    age_max: 11,
    city: "Toronto",
    province: "ON",
    price: 65,
    schedule: "Tuesdays & Thursdays, 5:30 PM - 6:30 PM",
    spots_available: 14,
    session_type: "Multiple Sessions",
    description:
      "Build a strong skating foundation with certified power skating instructor Jodi Figliomeni. Focus on balance, stride technique, crossovers, and edge work for young competitive players.",
  },
  {
    id: 4,
    title: "Advanced Power Skating Camp",
    coach: "Jodi Figliomeni - JF Power Elite",
    sport: "Power Skating",
    skill_level: "AA/AAA",
    age_min: 11,
    age_max: 15,
    city: "Toronto",
    province: "ON",
    price: 280,
    schedule: "March Break — March 10–14, 9:00 AM - 12:00 PM",
    spots_available: 10,
    session_type: "Camp",
    description:
      "Intensive 5-day power skating camp for competitive players. Advanced techniques including backward skating, tight turns, explosive acceleration, and game-speed agility.",
  },
  {
    id: 5,
    title: "Strength & Conditioning for Hockey",
    coach: "CJ McCartney - Advance Hockey Lab",
    sport: "Personal Fitness",
    skill_level: "AA/AAA",
    age_min: 14,
    age_max: 18,
    city: "Newmarket",
    province: "ON",
    price: 55,
    schedule: "Mondays & Wednesdays, 4:00 PM - 5:00 PM",
    spots_available: 8,
    session_type: "Multiple Sessions",
    description:
      "Sport-specific strength and conditioning designed for competitive hockey players. Build explosive power, speed, and endurance with NHL-level training methods and periodized programming.",
  },
  {
    id: 6,
    title: "Elite Athletic Performance Training",
    coach: "CJ McCartney - Advance Hockey Lab",
    sport: "Personal Fitness",
    skill_level: "Elite/Pro",
    age_min: 15,
    age_max: 20,
    city: "Newmarket",
    province: "ON",
    price: 70,
    schedule: "Fridays, 3:30 PM - 5:00 PM",
    spots_available: 6,
    session_type: "Single Session",
    description:
      "One-on-one elite performance training for serious athletes. Custom programming focused on injury prevention, explosive power, and peak athletic performance tailored to your sport.",
  },
  {
    id: 7,
    title: "Basketball Skills Academy",
    coach: "Moud Basketball Training",
    sport: "Basketball",
    skill_level: "A/AA",
    age_min: 10,
    age_max: 14,
    city: "Mississauga",
    province: "ON",
    price: 50,
    schedule: "Saturdays, 11:00 AM - 12:30 PM",
    spots_available: 8,
    session_type: "Multiple Sessions",
    description:
      "Develop core basketball skills including ball handling, shooting form, defensive footwork, and game awareness. Small group training ensures personalized coaching and maximum reps.",
  },
  {
    id: 8,
    title: "March Break Basketball Camp",
    coach: "Moud Basketball Training",
    sport: "Basketball",
    skill_level: "C/B",
    age_min: 8,
    age_max: 12,
    city: "Mississauga",
    province: "ON",
    price: 225,
    schedule: "March Break — March 10–14, 10:00 AM - 2:00 PM",
    spots_available: 20,
    session_type: "Camp",
    description:
      "Fun and engaging basketball camp perfect for beginners and intermediate players. Daily skills challenges, scrimmages, and a final tournament on the last day with trophies for all participants.",
  },
  {
    id: 9,
    title: "Hockey Development Program",
    coach: "Eagle Athletics",
    sport: "Hockey",
    skill_level: "A/AA",
    age_min: 9,
    age_max: 13,
    city: "Ottawa",
    province: "ON",
    price: 60,
    schedule: "Wednesdays, 6:00 PM - 7:30 PM",
    spots_available: 18,
    session_type: "Multiple Sessions",
    description:
      "Structured hockey development program focusing on fundamental skills, team play concepts, and game-ready drills. Ideal for players looking to move up to the next competitive level.",
  },
  {
    id: 10,
    title: "Spring Hockey Showcase Camp",
    coach: "Eagle Athletics",
    sport: "Hockey",
    skill_level: "AAA",
    age_min: 12,
    age_max: 16,
    city: "Ottawa",
    province: "ON",
    price: 350,
    schedule: "April 5–7, 8:00 AM - 4:00 PM",
    spots_available: 24,
    session_type: "Camp",
    description:
      "Three-day elite showcase camp with evaluations from scouts and coaches. Includes on-ice sessions, off-ice training, video review, and a final showcase game.",
  },
  {
    id: 11,
    title: "Pro Skills Hockey Training",
    coach: "RHA Hockey Academy",
    sport: "Hockey",
    skill_level: "AA/AAA",
    age_min: 10,
    age_max: 14,
    city: "Toronto",
    province: "ON",
    price: 80,
    schedule: "Thursdays, 7:00 PM - 8:30 PM",
    spots_available: 12,
    session_type: "Multiple Sessions",
    description:
      "High-tempo skills sessions led by professional coaches with OHL and NCAA experience. Focus on skating, shooting, puck protection, and competitive battle drills.",
  },
  {
    id: 12,
    title: "Goalie-Specific Training",
    coach: "RHA Hockey Academy",
    sport: "Hockey",
    skill_level: "AA/AAA",
    age_min: 11,
    age_max: 16,
    city: "Toronto",
    province: "ON",
    price: 90,
    schedule: "Sundays, 3:00 PM - 4:30 PM",
    spots_available: 6,
    session_type: "Multiple Sessions",
    description:
      "Specialized goaltender training focusing on positioning, movement, reflexes, and mental preparation. Small group format ensures maximum reps and individual feedback from experienced goalie coaches.",
  },
];
